const API_DEFAULT=(location.protocol==='file:')?'http://localhost:8787/api':'/api';
const API=localStorage.getItem('hh_api_base')||window.HOMEHERO_API_BASE||API_DEFAULT;
const AI_MODEL_STORE='homehero_ai_settings_v1';
const CUSTOMER_CARE='thanigailakshmi2908@gmail.com';
const STORE='homehero_ultimate_v3';
const services=[
{id:'cleaning',icon:'🧹',name:'Home Cleaning',desc:'Hourly / deep cleaning',price:199,tag:'Most booked'},
{id:'plumber',icon:'🔧',name:'Plumber',desc:'Repairs & installation',price:179,tag:'Fast response'},
{id:'electrician',icon:'⚡',name:'Electrician',desc:'Electrical repairs',price:179,tag:'Verified pros'},
{id:'maid',icon:'🧺',name:'Maid / Helper',desc:'Daily & monthly help',price:249,tag:'Flexible'},
{id:'ac',icon:'❄️',name:'AC Service',desc:'Service & repair',price:349,tag:'Seasonal'},
{id:'appliance',icon:'🛠️',name:'Appliance Repair',desc:'Home appliances',price:229,tag:'Popular'},
{id:'painting',icon:'🎨',name:'Painting',desc:'Room & full-home',price:499,tag:'Home makeover'},
{id:'pest',icon:'🐜',name:'Pest Control',desc:'Home treatment',price:449,tag:'Safe care'},
{id:'carpenter',icon:'🪚',name:'Carpenter',desc:'Furniture & fittings',price:229,tag:'Verified'},
{id:'moving',icon:'📦',name:'Home Shifting',desc:'Local moving help',price:649,tag:'On demand'},
{id:'gardener',icon:'🌱',name:'Gardener',desc:'Garden maintenance',price:249,tag:'Home care'},
{id:'water',icon:'🚰',name:'Water / Tank',desc:'Cleaning & repairs',price:299,tag:'Essential'}
];
let state={
 screen:'home',role:'customer',service:null,booking:null,bookings:[],user:localStorage.hh_user||'',
 phone:localStorage.hh_phone||'',logged:!!localStorage.hh_user,token:localStorage.hh_token||'',
 speed:'standard',coords:null,loading:false,query:'',otpSent:false,otpExpiresAt:0,notifyEnabled:false
};

function loadLocal(){
 try{
  const d=JSON.parse(localStorage.getItem(STORE)||'{}');
  state.bookings=d.bookings||[];
  state.coords=d.coords||null;state.notifyEnabled=localStorage.hh_notify==='1';
 }catch{}
}
function saveLocal(){
 localStorage.setItem(STORE,JSON.stringify({bookings:state.bookings,coords:state.coords}));
}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(message,type='info'){
 const x=document.createElement('div');x.className=`toast ${type}`;x.innerHTML=`<span>${type==='ok'?'✓':type==='error'?'!':'i'}</span>${esc(message)}`;
 document.body.appendChild(x);setTimeout(()=>x.classList.add('show'),20);setTimeout(()=>{x.classList.remove('show');setTimeout(()=>x.remove(),250)},2600);
}
function setLoading(on,label='Loading…'){
 state.loading=on;let el=document.getElementById('loading');
 if(on){if(!el){el=document.createElement('div');el.id='loading';el.className='loading-screen';document.body.appendChild(el)}el.innerHTML=`<div class="loader-orbit"><div></div></div><b>${esc(label)}</b><span>Please wait</span>`}
 else if(el)el.remove();
}
async function demoApi(path,opt={}){
 const body=opt.body?JSON.parse(opt.body):{};
 if(path==='/auth/request-otp')return {sent:true,devOtp:'123456',demo:true};
 if(path==='/auth/verify-otp'){
  const u={id:'DEMO-'+Date.now(),name:'HomeHero User',phone:body.phone,role:'customer'};
  return {token:'demo-'+Date.now(),user:u,demo:true};
 }
 if(path==='/bookings'&&opt.method==='POST'){
  const s=services.find(x=>x.id===body.serviceId)||services[0],h=Math.max(1,+body.hours||1),fast=body.express?39:0;
  const labour=s.price*h,discount=Math.min(30,Math.floor(labour*.05));
  return {id:'HH'+Date.now().toString().slice(-8),serviceId:s.id,serviceName:s.name,hours:h,address:body.address||'Saved Home Address',notes:body.notes||'',express:!!body.express,status:'assigned',total:labour+39+7+fast-discount,worker:{id:'W-DEMO',name:'HomeHero Professional',role:s.name,rating:4.9,jobs:120,eta:body.express?18:38,initials:'HP'},createdAt:new Date().toISOString()};
 }
 if(path==='/bookings'&&(!opt.method||opt.method==='GET'))return {bookings:state.bookings};
 if(path.startsWith('/bookings/')&&path.endsWith('/dispatch'))return {status:'assigned',worker:{id:'W-DEMO',name:'HomeHero Professional',role:state.booking?.serviceName||'Professional',rating:4.9,jobs:120,eta:18,initials:'HP'}};
 if(path.startsWith('/bookings/')&&path.endsWith('/cancel'))return {ok:true,status:'cancelled'};
 if(path==='/payments/create')return {ok:true,message:'Demo payment successful',payment:{provider:'demo',status:'paid',id:'PAY'+Date.now()}};
 if(path==='/workers/apply')return {id:'WA'+Date.now(),status:'pending_review',message:'Application saved. Operations will review it.'};
 if(path==='/support/tickets')return {id:'CASE'+Date.now(),status:'open',message:'Support case created.'};
 if(path==='/ai/chat')return {provider:'local',model:'HomeHero Smart Support',text:localAI(body.messages?.at(-1)?.content||'')};
 if(path==='/profile')return {user:{name:state.user,phone:state.phone,role:state.role}};
 if(path==='/admin/summary')return {bookings:state.bookings.length,workers:3,pendingWorkers:1,users:1,paidBookings:state.bookings.filter(b=>b.status==='paid').length};
 return {ok:true};
}
async function api(path,opt={}){
 const headers={'Content-Type':'application/json',...(opt.headers||{})};
 if(state.token)headers.Authorization=`Bearer ${state.token}`;
 try{
  const r=await fetch(API+path,{...opt,headers});
  const d=await r.json().catch(()=>({}));
  if(!r.ok)throw Error(d.error||'Request failed');
  return d;
 }catch(e){
  if(location.protocol==='file:'||location.hostname.endsWith('github.io')||String(e.message).includes('Failed to fetch'))return demoApi(path,opt);
  throw e;
 }
}
function localAI(q){
 const x=q.toLowerCase();
 if(/leak|tap|pipe|water/.test(x))return 'For a leaking tap or pipe, choose Plumber. If water is near electrical equipment, switch off the affected power safely and avoid touching wet electrical parts. Add a photo/description in the booking notes so the professional arrives prepared.';
 if(/clean|house|dust|bathroom/.test(x))return 'For routine or deep household cleaning, choose Home Cleaning. You can select the duration, add room-specific instructions and choose Standard or Express arrival.';
 if(/ac|air.?condition/.test(x))return 'Choose AC Service for cooling issues, cleaning or routine maintenance. Describe the symptom in the booking notes and avoid attempting electrical repairs yourself.';
 if(/price|cost|₹|rupee|charge/.test(x))return 'HomeHero shows the service estimate before confirmation. The total can include labour, travel, platform and optional Express fees, with applicable offers shown separately.';
 if(/book|booking|schedule/.test(x))return 'Choose a service, enter the service address, select duration and arrival speed, review the total, then confirm. Your booking can be opened from Bookings for status and payment.';
 if(/worker|professional|maid|helper/.test(x))return 'HomeHero can match verified professionals by service and location. Worker onboarding includes identity, skills and operations review before approval.';
 return 'I can help you choose a HomeHero service, understand pricing, prepare a booking, or handle support. Tell me what is happening at your home and when you need help.';
}
function render(){
 const app=document.getElementById('app');
 app.innerHTML=`<div class="app-bg"><i></i><i></i><i></i><i></i></div>
 <div class="shell">
  <header class="top">
   <button class="brand" onclick="go('home')" aria-label="HomeHero home"><span class="logo"><span>⌂</span></span><span>HomeHero<small>HOME SERVICES</small></span></button>
   <div class="top-actions"><button class="status-pill" onclick="locationRequest()">📍 <span id="locpill">${state.coords?'Location enabled':'Enable location'}</span></button><button class="profile-pill" onclick="openProfile()">👤 ${esc(state.logged?state.user:'Guest')}</button></div>
  </header>
  <main class="page">${screenHTML()}</main>
  <footer class="site-footer"><div class="creator"><b>HomeHero</b> · Created by <strong>Deepak.T</strong></div><a href="mailto:${CUSTOMER_CARE}">Customer Care · ${CUSTOMER_CARE}</a><span>Affordable · Verified · Trusted household services</span></footer>
  ${state.logged?navHTML():''}
 </div>${!state.logged?loginHTML():''}`;
}
function navHTML(){return `<footer class="bottom"><nav class="nav">
 <button class="${state.screen==='home'?'active':''}" onclick="go('home')"><span>⌂</span><small>Home</small></button>
 <button class="${state.screen==='bookings'?'active':''}" onclick="go('bookings')"><span>▣</span><small>Bookings</small></button>
 <button class="${state.screen==='offers'?'active':''}" onclick="go('offers')"><span>🎁</span><small>Offers</small></button>
 <button class="${state.screen==='support'?'active':''}" onclick="go('support')"><span>◉</span><small>Support</small></button>
 <button class="${state.screen==='more'?'active':''}" onclick="go('more')"><span>☰</span><small>More</small></button>
 </nav></footer>`}
function loginHTML(){
 return `<div class="overlay"><div class="auth-modal">
 <div class="auth-glow"></div><div class="brand"><span class="logo"><span>⌂</span></span><span>HomeHero<small>YOUR HOME. OUR HEROES.</small></span></div>
 <div class="auth-hero"><span class="eyebrow">SECURE ACCESS</span><h1>Help at home,<br><em>without the hassle.</em></h1><p>Phone OTP · verified professionals · live dispatch · transparent pricing · AI support.</p></div>
 <div class="auth-form">${state.otpSent?otpHTML():phoneHTML()}</div>
 <div class="creator">✨ <b>Created by Deepak.T</b><br><span>Customer Care: ${CUSTOMER_CARE}</span></div>
 </div></div>`;
}
function phoneHTML(){return `<label class="field-label">Mobile number</label><div class="phone-field"><span>🇮🇳 +91</span><input id="phone" class="input" placeholder="10-digit mobile number" inputmode="numeric" maxlength="10" autofocus></div><button class="btn primary full glow" onclick="sendOtp()">Continue with OTP <span>→</span></button><p class="hint">A one-time password will be sent to verify your mobile.</p><div class="auth-divider"><span>PREVIEW</span></div><div class="row"><button class="btn alt full" onclick="workerPreview()">👷 Worker preview</button><button class="btn alt full" onclick="adminPreview()">🛡️ Admin preview</button></div>`}
function otpHTML(){return `<button class="back-link" onclick="state.otpSent=false;render()">← Change number</button><label class="field-label">Enter verification code</label><p class="hint">OTP sent to <b>+91 ${esc(state.phone)}</b></p><input id="otp" class="input otp-input" maxlength="6" inputmode="numeric" placeholder="• • • • • •" autofocus><button class="btn primary full glow" onclick="verifyOtp()">Verify & Open HomeHero <span>✓</span></button><button class="text-btn" onclick="sendOtp(true)">Resend OTP</button>${state.otpDemo?`<div class="demo-otp">Demo mode OTP: <b>${state.otpDemo}</b></div>`:''}`}
async function sendOtp(resend=false){
 const p=(document.getElementById('phone')?.value||state.phone).replace(/\D/g,'');
 if(!/^\d{10}$/.test(p))return toast('Enter a valid 10-digit mobile number','error');
 state.phone=p;setLoading(true,resend?'Resending secure OTP…':'Sending secure OTP…');
 try{const d=await api('/auth/request-otp',{method:'POST',body:JSON.stringify({phone:p})});state.otpSent=true;state.otpDemo=d.devOtp||'';state.otpExpiresAt=Date.now()+5*60*1000;render();startOtpTicker();toast(d.demo?'Demo OTP generated.':'OTP sent to your mobile.','ok')}catch(e){toast(e.message,'error')}finally{setLoading(false)}
}
async function verifyOtp(){
 const otp=(document.getElementById('otp')?.value||'').replace(/\D/g,'');if(otp.length!==6)return toast('Enter the 6-digit OTP','error');
 setLoading(true,'Verifying your account…');
 try{const d=await api('/auth/verify-otp',{method:'POST',body:JSON.stringify({phone:state.phone,otp})});state.logged=true;state.user=d.user?.name||'HomeHero User';state.token=d.token||'demo-token';localStorage.hh_user=state.user;localStorage.hh_phone=state.phone;localStorage.hh_token=state.token;render();locationRequest();toast('Welcome to HomeHero','ok')}catch(e){toast(e.message,'error')}finally{setLoading(false)}
}
function startOtpTicker(){clearInterval(window.__hhOtpTimer);window.__hhOtpTimer=setInterval(()=>{if(!state.otpSent||Date.now()>=state.otpExpiresAt){clearInterval(window.__hhOtpTimer);return}const hint=document.querySelector('.auth-form .hint');if(hint){const r=Math.max(0,Math.ceil((state.otpExpiresAt-Date.now())/1000));hint.innerHTML=`OTP sent to <b>+91 ${esc(state.phone)}</b> · expires in <b>${Math.floor(r/60)}:${String(r%60).padStart(2,'0')}</b>`}},1000)}
function notify(title,body){try{if(state.notifyEnabled&&'Notification' in window&&Notification.permission==='granted')new Notification(title,{body,icon:'manifest.json',tag:'homehero'})}catch{}}
async function enableNotifications(){if(!('Notification' in window))return toast('Notifications are not supported on this browser','error');const p=await Notification.requestPermission();state.notifyEnabled=p==='granted';localStorage.hh_notify=state.notifyEnabled?'1':'0';toast(state.notifyEnabled?'Device notifications enabled':'Notification permission not granted',state.notifyEnabled?'ok':'error')}
function openMaps(){const b=state.booking;if(!b)return;if(b.lat!=null&&b.lng!=null)window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(b.lat+','+b.lng)}`,'_blank');else window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(b.address||'Chennai, India')}`,'_blank')}
function workerPreview(){state.logged=true;state.role='worker';state.user='Worker Preview';state.token='demo-worker';localStorage.hh_user=state.user;state.screen='worker';render()}
function adminPreview(){state.logged=true;state.role='admin';state.user='Admin Preview';state.token='demo-admin';localStorage.hh_user=state.user;state.screen='admin';render()}
function openProfile(){state.screen='profile';render()}
function go(s){state.screen=s;render();window.scrollTo({top:0,behavior:'smooth'})}
function screenHTML(){switch(state.screen){case'home':return home();case'bookings':return bookings();case'offers':return offers();case'support':return support();case'profile':return profile();case'checkout':return checkout();case'track':return track();case'worker':return workerDash();case'admin':return adminDash();case'more':return more();case'ai':return aiAssistant();case'apply':return applyWorker();case'service':return serviceDetails();default:return home()}}
function home(){
 return `<section class="hero hero-home"><div class="hero-copy"><span class="eyebrow">HOMEHERO · SMART HOME SERVICES</span><h1>Every home job.<br><em>One trusted app.</em></h1><p>Book verified professionals for cleaning, plumbing, electrical work, AC service and more — with smart matching and clear pricing.</p><div class="hero-actions"><button class="btn primary glow" onclick="document.getElementById('serviceSearch').focus()">Find a service <span>⌕</span></button><button class="btn glass" onclick="go('ai')">🤖 Ask HomeHero AI</button></div><div class="trust-row"><span>✓ Verified pros</span><span>✓ Clear total</span><span>✓ Support</span></div></div><div class="hero-orb"><div class="orb-core">⌂</div><div class="orb-ring r1"></div><div class="orb-ring r2"></div><div class="orb-ring r3"></div><span class="orb-chip c1">⚡ Fast</span><span class="orb-chip c2">🛡️ Verified</span><span class="orb-chip c3">🤖 AI</span></div></section>
 <div class="search-panel glass-panel"><div class="search-box"><span>⌕</span><input id="serviceSearch" class="input" value="${esc(state.query)}" placeholder="What do you need help with?" oninput="filterServices(this.value)"><button class="btn alt" onclick="locationRequest()">📍 Nearby</button></div><div class="quick-tags"><button onclick="quickSearch('cleaning')">🧹 Cleaning</button><button onclick="quickSearch('plumber')">🔧 Plumber</button><button onclick="quickSearch('electrician')">⚡ Electrician</button><button onclick="quickSearch('ac')">❄️ AC Service</button><button onclick="quickSearch('maid')">🧺 Maid</button></div></div>
 <div class="section"><div><span class="eyebrow">EXPLORE</span><h2>Popular services</h2></div><span class="badge">Starting from ₹179</span></div><div id="services" class="grid services-grid">${services.map(serviceCard).join('')}</div>
 <div class="feature-strip"><div><b>🛡️ Real-worker onboarding</b><span>Identity → skills → approval → jobs.</span></div><div><b>📍 Smart dispatch</b><span>Location-aware matching and ETA.</span></div><div><b>💰 Clear economics</b><span>Customer total and worker payout stay visible.</span></div><div><b>🤖 AI layer</b><span>Support, intent and service guidance.</span></div></div>
 <section class="how-section"><span class="eyebrow">HOW IT WORKS</span><h2>From problem to professional in minutes.</h2><div class="how-grid"><div><i>01</i><b>Tell us what you need</b><span>Pick a service or ask HomeHero AI.</span></div><div><i>02</i><b>Choose your visit</b><span>Address, duration and Standard/Express arrival.</span></div><div><i>03</i><b>Meet your professional</b><span>See verification, ETA and booking status.</span></div><div><i>04</i><b>Complete with confidence</b><span>Review payment, invoice and support options.</span></div></div></section>`;
}
function serviceCard(s){return `<button class="card service-card" onclick="choose('${s.id}')"><span class="service-top"><span class="service-icon">${s.icon}</span><span class="service-tag">${s.tag}</span></span><span class="service-name">${esc(s.name)}</span><span class="small">${esc(s.desc)}</span><span class="service-bottom"><strong>From ₹${s.price}</strong><span>Book →</span></span></button>`}
function filterServices(q){state.query=q;const el=document.getElementById('services');if(el)el.innerHTML=services.filter(s=>(s.name+' '+s.desc+' '+s.tag).toLowerCase().includes(q.toLowerCase())).map(serviceCard).join('')||`<div class="empty-card">No matching service. Try Home Cleaning, Plumber, AC or Maid.</div>`}
function quickSearch(q){state.query=q;render();setTimeout(()=>{const e=document.getElementById('serviceSearch');e?.focus();e?.scrollIntoView({behavior:'smooth',block:'center'})},50)}
function choose(id){state.service=services.find(s=>s.id===id);state.screen='service';render()}
function serviceDetails(){const s=state.service;return `<div class="back-link" onclick="go('home')">← All services</div><section class="detail-hero"><div class="big-service-icon">${s.icon}</div><div><span class="eyebrow">${esc(s.tag)}</span><h1>${esc(s.name)}</h1><p>${esc(s.desc)} with verified professional matching and transparent checkout.</p><div class="rating-line">★ 4.9 · 500+ completed jobs · Verified professionals</div><div class="price-cards"><div><span>Hourly starting</span><b>₹${s.price}/hr</b></div><div><span>Monthly estimate</span><b>₹${Math.round(s.price*4*26*.9).toLocaleString('en-IN')}</b><small>4h/day · 26 days · 10% plan estimate</small></div></div></div></section><div class="detail-grid"><div class="glass-panel detail-copy"><h2>What you get</h2><p>Professional service at your home with clear pricing before confirmation. Add notes and location details so the professional can prepare.</p><div class="check-list"><span>✓ Upfront estimate</span><span>✓ Location-aware matching</span><span>✓ Booking support</span><span>✓ Digital payment/invoice flow</span></div></div><div class="card booking-cta"><span class="small">Starting price</span><strong>₹${s.price}</strong><button class="btn primary glow full" onclick="state.screen='checkout';render()">Book ${esc(s.name)} →</button></div></div>`}
function quote(s,h,sp){const labour=s.price*h,travel=39,platform=7,express=sp==='express'?39:0,discount=Math.min(30,Math.floor(labour*.05)),total=labour+travel+platform+express-discount;return {labour,travel,platform,express,discount,total}}
function checkout(){
 const s=state.service;if(!s)return home();const q=quote(s,1,state.speed);
 return `<div class="back-link" onclick="go('service')">← Back to ${esc(s.name)}</div><div class="checkout-head"><div><span class="eyebrow">SECURE BOOKING</span><h1>Book your service</h1><p>Everything is shown before you confirm.</p></div><span class="step-badge">STEP 1 OF 2</span></div>
 <div class="checkout-grid"><div class="card form-card"><div class="form-title"><span>01</span><div><h2>Service details</h2><small>${esc(s.name)}</small></div></div><label class="field-label">Visit address</label><div class="row"><input id="address" class="input" placeholder="House / flat, street, area" value="${esc(state.coords?`Near ${state.coords.lat.toFixed(3)}, ${state.coords.lng.toFixed(3)}`:'')}"><button class="btn alt" onclick="locationRequest()">📍 GPS</button></div><label class="field-label">Duration</label><select id="duration" class="input" onchange="updateBill()"><option value="1">1 hour</option><option value="2">2 hours</option><option value="4">4 hours</option><option value="8">8 hours</option></select><label class="field-label">Instructions for your professional</label><textarea id="notes" class="input" rows="4" placeholder="Describe the problem, room, appliance or special instructions…"></textarea></div>
 <div class="card form-card"><div class="form-title"><span>02</span><div><h2>Arrival</h2><small>Choose your preferred speed</small></div></div><button id="standardBtn" class="choice ${state.speed==='standard'?'selected':''}" onclick="setSpeed('standard')"><span>🕒<b>Standard</b><small>30–60 min · included</small></span><i>✓</i></button><button id="expressBtn" class="choice ${state.speed==='express'?'selected':''}" onclick="setSpeed('express')"><span>⚡<b>Express</b><small>15–30 min · +₹39</small></span><i>✓</i></button><div class="bill" id="bill">${billHTML(q)}</div></div></div>`;
}
function billHTML(q){return `<div class="bill-row"><span>Service</span><b>₹${q.labour}</b></div><div class="bill-row"><span>Travel</span><span>₹${q.travel}</span></div><div class="bill-row"><span>Platform</span><span>₹${q.platform}</span></div>${q.express?`<div class="bill-row"><span>Express</span><span>₹${q.express}</span></div>`:''}<div class="bill-row discount"><span>HomeHero offer</span><span>−₹${q.discount}</span></div><div class="bill-total"><span>Total</span><strong>₹${q.total}</strong></div><button class="btn primary glow full" onclick="confirmBooking()">Confirm & continue →</button><small>Payment is requested only after you review the booking.</small>`}
function setSpeed(x){state.speed=x;updateBill();document.querySelectorAll('.choice').forEach(e=>e.classList.remove('selected'));document.getElementById(x+'Btn')?.classList.add('selected')}
function updateBill(){const h=+(document.getElementById('duration')?.value||1);const q=quote(state.service,h,state.speed);const b=document.getElementById('bill');if(b)b.innerHTML=billHTML(q)}
async function confirmBooking(){
 const address=document.getElementById('address')?.value.trim();if(!address)return toast('Please enter your service address','error');
 const h=+(document.getElementById('duration')?.value||1);
 setLoading(true,'Creating your secure booking…');
 try{const b=await api('/bookings',{method:'POST',body:JSON.stringify({serviceId:state.service.id,hours:h,address,notes:document.getElementById('notes')?.value.trim()||'',express:state.speed==='express',lat:state.coords?.lat,lng:state.coords?.lng})});state.booking=b;state.bookings.unshift(b);saveLocal();state.screen='track';render();await refreshMatch(false);notify('HomeHero booking created',`${b.serviceName} · ₹${b.total}`);toast('Booking created','ok')}catch(e){toast(e.message,'error')}finally{setLoading(false)}
}
function track(){
 const b=state.booking;if(!b)return bookings();const status=(b.status||'searching').replace('_',' ');
 return `<div class="track-head"><div><span class="eyebrow">BOOKING · ${esc(b.id)}</span><h1>${state.service?.icon||'🏠'} ${esc(b.serviceName||state.service?.name||'Home service')}</h1><p>${esc(b.address)} · ${b.hours} hour${b.hours>1?'s':''}</p></div><span class="live-badge"><i></i>${esc(status)}</span></div>
 <div class="track-layout"><div><div class="map real-map"><div class="map-grid"></div><span class="map-road a"></span><span class="map-road b"></span><span class="map-pin">📍</span><div class="map-label">${b.lat!=null?'GPS location captured':'Service address saved'}</div><button class="map-open" onclick="openMaps()">↗ Open in Maps</button></div><div class="card worker-card"><div class="worker-avatar">${esc(b.worker?.initials||'HH')}</div><div class="worker-main"><b>${esc(b.worker?.name||'Finding a nearby professional…')}</b><span>${esc(b.worker?.role||state.service?.name||'Verified professional')} · ★ ${b.worker?.rating||'—'}</span><small>${b.worker?.jobs||0} completed jobs · identity verified</small></div><button class="icon-btn" onclick="toast('Secure calling is available when telephony is configured.')">☎</button></div></div>
 <div class="card timeline"><h2>Booking progress</h2><div class="timeline-item done"><i>✓</i><div><b>Booking confirmed</b><span>Service request received.</span></div></div><div class="timeline-item ${b.worker?'done':''}"><i>${b.worker?'✓':'2'}</i><div><b>Professional matched</b><span>${b.worker?`ETA about ${b.worker.eta||18} minutes.`:'Searching verified professionals nearby.'}</span></div></div><div class="timeline-item"><i>3</i><div><b>Service starts</b><span>Start verification can be enabled in production.</span></div></div><div class="timeline-item"><i>4</i><div><b>Complete & invoice</b><span>Payment and payout records are created after completion.</span></div></div><div class="row"><button class="btn alt" onclick="refreshMatch()">↻ Refresh</button><button class="btn alt" onclick="go('support')">Need help?</button></div></div></div>
 <div class="card total-card"><div><span class="small">Booking total</span><strong>₹${b.total}</strong></div><div class="row"><button class="btn primary glow" onclick="pay()">Pay / continue</button><button class="btn danger" onclick="cancelBooking()">Cancel booking</button></div>${b.status==='completed'||b.status==='paid'?`<div class="rating-box"><b>Rate this service</b><div class="rating-actions">${[1,2,3,4,5].map(n=>`<button onclick="rateBooking(${n})">${n}★</button>`).join('')}</div></div>`:''}</div>`;
}
async function refreshMatch(show=true){if(!state.booking)return;try{const d=await api(`/bookings/${state.booking.id}/dispatch`,{method:'POST'});state.booking={...state.booking,...d};state.bookings=state.bookings.map(x=>x.id===state.booking.id?state.booking:x);saveLocal();render();if(show)toast('Matching refreshed','ok')}catch(e){toast(e.message,'error')}}
async function cancelBooking(){if(!confirm('Cancel this booking?'))return;try{const d=await api(`/bookings/${state.booking.id}/cancel`,{method:'POST'});state.booking={...state.booking,...d};state.bookings=state.bookings.map(x=>x.id===state.booking.id?state.booking:x);saveLocal();toast('Booking cancelled','ok');go('bookings')}catch(e){toast(e.message,'error')}}
async function pay(){setLoading(true,'Preparing secure payment…');try{const d=await api('/payments/create',{method:'POST',body:JSON.stringify({bookingId:state.booking.id})});if(d.live&&d.order){if(!window.Razorpay)throw Error('Razorpay checkout is not loaded');const rzp=new Razorpay({key:d.keyId,amount:d.order.amount,currency:d.order.currency,name:'HomeHero',description:state.booking.serviceName,order_id:d.order.id,prefill:{name:state.user,contact:state.phone?'+91'+state.phone:''},theme:{color:'#825cff'},handler:async(response)=>{setLoading(true,'Verifying payment…');try{const c=await api('/payments/confirm',{method:'POST',body:JSON.stringify({bookingId:state.booking.id,paymentId:response.razorpay_payment_id,orderId:response.razorpay_order_id,signature:response.razorpay_signature})});state.booking.status='paid';state.booking.payment=c.payment;state.bookings=state.bookings.map(x=>x.id===state.booking.id?state.booking:x);saveLocal();notify('HomeHero payment confirmed',`Booking ${state.booking.id}`);toast('Payment verified successfully','ok');go('bookings')}catch(e){toast(e.message,'error')}finally{setLoading(false)}}});rzp.on('payment.failed',()=>toast('Payment was not completed. No booking payment was marked as paid.','error'));rzp.open();return;}state.booking.status='paid';state.booking.payment=d.payment;state.bookings=state.bookings.map(x=>x.id===state.booking.id?state.booking:x);saveLocal();notify('HomeHero payment recorded',`Booking ${state.booking.id}`);toast(d.message||'Demo payment successful','ok');setTimeout(()=>go('bookings'),500)}catch(e){toast(e.message,'error')}finally{setLoading(false)}}
async function rateBooking(rating){try{await api(`/bookings/${state.booking.id}/rating`,{method:'POST',body:JSON.stringify({rating})});state.booking.rating=rating;toast(`Thanks — ${rating} star rating saved`,'ok')}catch(e){toast(e.message,'error')}}
async function bookings(){
 let items=state.bookings;try{const d=await api('/bookings');if(Array.isArray(d.bookings))items=d.bookings;state.bookings=items;saveLocal()}catch{}
 return `<section class="page-title"><span class="eyebrow">YOUR HOMEHERO</span><h1>Bookings</h1><p>Track upcoming and previous household services.</p><button class="btn primary glow" onclick="go('home')">+ New booking</button></section>${items.length?`<div class="booking-list">${items.map((b,i)=>`<div class="card booking-row"><div class="booking-icon">${services.find(s=>s.id===b.serviceId)?.icon||'🏠'}</div><div class="booking-info"><b>${esc(b.serviceName)}</b><span>${esc(b.address||'Saved address')} · ${b.hours}h</span><small>${new Date(b.createdAt||Date.now()).toLocaleString()}</small></div><span class="status-chip ${b.status}">${esc(b.status)}</span><button class="btn alt" onclick='openBooking(${JSON.stringify(b).replace(/'/g,"&#39;")})'>Open</button></div>`).join('')}</div>`:`<div class="empty-state"><div>🏠</div><h2>No bookings yet</h2><p>Your confirmed services will appear here.</p><button class="btn primary glow" onclick="go('home')">Explore services</button></div>`}`;
}
function openBooking(b){state.booking=b;state.service=services.find(s=>s.id===b.serviceId)||state.service;state.screen='track';render()}
function offers(){const offers=[['₹50 OFF','First booking','Use on eligible services'],['5% OFF','Repeat booking','For selected repeat customers'],['₹100 CREDIT','Refer a friend','Credit after eligible referral'],['15% OFF','Cleaning offer','Selected cleaning services'],['FREE TRAVEL','Selected services','Limited service areas'],['PLUS TRIAL','HomeHero Plus','Membership benefits']];return `<section class="page-title"><span class="eyebrow">HOMEHERO REWARDS</span><h1>Offers for your home.</h1><p>Save on eligible services. Exact eligibility is shown before checkout.</p></section><div class="offers-grid">${offers.map((o,i)=>`<div class="offer-card"><span class="offer-icon">${['🎟️','🔁','🎁','✨','🚗','👑'][i]}</span><span class="eyebrow">OFFER ${i+1}</span><h2>${o[0]}</h2><b>${o[1]}</b><p>${o[2]}</p><button class="btn alt full" onclick="toast('Offer saved to this session','ok')">Save offer</button></div>`).join('')}</div>`}
function support(){return `<section class="support-hero"><span class="eyebrow">SUPPORT & SAFETY</span><h1>Help when you<br><em>need it.</em></h1><p>AI support for quick answers and customer care for booking, payment, service and safety issues.</p></section><div class="support-grid"><div class="card support-card ai-card"><span>🤖</span><h2>HomeHero AI</h2><p>Ask about services, pricing, booking or what to do next.</p><button class="btn primary glow" onclick="go('ai')">Start AI support →</button></div><div class="card support-card"><span>✉️</span><h2>Customer Care</h2><p>${CUSTOMER_CARE}</p><a class="btn alt inline-btn" href="mailto:${CUSTOMER_CARE}">Email us</a></div><div class="card support-card safety"><span>🛡️</span><h2>Safety report</h2><p>Report a safety concern or urgent service issue.</p><button class="btn danger" onclick="openTicket('safety')">Report safely</button></div><div class="card support-card"><span>💰</span><h2>Billing dispute</h2><p>Open a support case with your booking ID and issue.</p><button class="btn alt" onclick="openTicket('billing')">Raise issue</button></div></div>`}
function openTicket(type){const subject=prompt(type==='safety'?'Describe the safety concern:':'Describe the billing/service issue:');if(!subject)return;api('/support/tickets',{method:'POST',body:JSON.stringify({type,subject,bookingId:state.booking?.id||null})}).then(d=>toast(d.message||'Case created','ok')).catch(e=>toast(e.message,'error'))}
function profile(){return `<section class="page-title"><span class="eyebrow">ACCOUNT</span><h1>Profile & settings</h1><p>Manage your account, location and privacy controls.</p></section><div class="profile-grid"><div class="profile-card glass-panel"><div class="profile-avatar">${esc((state.user||'H').slice(0,1).toUpperCase())}</div><h2>${esc(state.user||'HomeHero User')}</h2><p>+91 ${esc(state.phone||'Mobile verified')}</p><span class="verified-pill">✓ Mobile verified</span><label class="field-label">Display name</label><input id="profileName" class="input" value="${esc(state.user)}"><button class="btn primary" onclick="saveProfile()">Save profile</button></div><div class="card"><h2>📍 Location</h2><p class="small">${state.coords?`GPS enabled · ±${Math.round(state.coords.accuracy||0)}m`:'Location is not enabled'}</p><button class="btn alt" onclick="locationRequest()">${state.coords?'Refresh location':'Enable location'}</button><hr><h2>🔐 Privacy</h2><p class="small">Location is requested only for service matching. API secrets stay on the backend.</p></div><div class="card"><h2>💳 Payments</h2><p class="small">Payment provider status is controlled by the backend configuration.</p><button class="btn alt" onclick="toast('Payment settings are protected by the backend.')">View status</button></div><div class="card"><h2>🔔 Notifications</h2><p class="small">Booking and support notifications can be connected to a push provider.</p><button class="btn alt" onclick="enableNotifications()">${state.notifyEnabled?'Enabled ✓':'Enable notifications'}</button></div></div><div class="card ai-settings"><h2>🤖 AI connection</h2><p class="small">For GitHub Pages, point this app to your deployed HomeHero backend. API keys stay on the backend and are never stored in the browser.</p><label class="field-label">Backend API URL</label><input id="apiBaseInput" class="input" value="${esc(localStorage.getItem('hh_api_base')||'')}" placeholder="https://your-backend.example.com/api"><button class="btn primary" onclick="saveApiBase()">Save & reload AI connection</button></div><button class="btn danger logout" onclick="logout()">Log out</button>`}
async function saveProfile(){const n=document.getElementById('profileName')?.value.trim();if(!n)return toast('Enter a name','error');state.user=n;localStorage.hh_user=n;try{await api('/profile',{method:'PATCH',body:JSON.stringify({name:n})})}catch{}render();toast('Profile updated','ok')}
function saveApiBase(){const v=document.getElementById('apiBaseInput')?.value.trim().replace(/\/$/,'');if(v&&!/^https?:\/\//.test(v))return toast('Use a full HTTPS backend URL ending in /api','error');if(v)localStorage.setItem('hh_api_base',v);else localStorage.removeItem('hh_api_base');toast('AI backend connection saved','ok');setTimeout(()=>location.reload(),350)}
function logout(){localStorage.removeItem('hh_user');localStorage.removeItem('hh_phone');localStorage.removeItem('hh_token');state={...state,logged:false,token:'',user:'',phone:'',screen:'home'};render()}
function workerDash(){return `<section class="page-title"><span class="eyebrow">WORKER APP</span><h1>Your work, <em>your control.</em></h1><p>Apply, verify, accept jobs, track earnings and prepare for payout.</p><button class="btn primary glow" onclick="go('apply')">Apply as a professional →</button></section><div class="kpi-grid"><div class="metric"><small>TODAY</small><strong>₹1,840</strong><span>8 jobs</span></div><div class="metric"><small>RATING</small><strong>4.9 ★</strong><span>Verified profile</span></div><div class="metric"><small>PAYOUT</small><strong>₹8,420</strong><span>Pending / available</span></div><div class="metric"><small>STATUS</small><strong>● Online</strong><span>Ready for matching</span></div></div><div class="section"><div><span class="eyebrow">JOB REQUESTS</span><h2>Nearby opportunities</h2></div><button class="btn alt" onclick="toast('Availability updated','ok')">● Online</button></div><div class="job-list">${['Kitchen tap repair','Fan installation','2-hour cleaning','AC inspection'].map((x,i)=>`<div class="card job-row"><div><b>${x}</b><span>${12+i*4} min away · estimated payout ₹${320+i*60}</span></div><button class="btn primary" onclick="toast('Job accepted in preview mode','ok')">Accept</button></div>`).join('')}</div><div class="section"><div><span class="eyebrow">ONBOARDING</span><h2>Verification checklist</h2></div></div><div class="check-grid">${['Mobile OTP','Identity / KYC','Address','Skills & certificates','Payout account','Operations approval'].map((x,i)=>`<div class="card check-card"><span>${i===0?'✓':'○'}</span><div><b>${x}</b><small>${i===0?'Complete':'Provider-ready step'}</small></div></div>`).join('')}</div>`}
function adminDash(){return `<section class="page-title"><span class="eyebrow">OPERATIONS CONTROL CENTER</span><h1>Operate <em>HomeHero.</em></h1><p>Monitor dispatch, workers, finance, safety, pricing and AI operations.</p></section><div id="adminStats" class="kpi-grid"><div class="metric"><small>BOOKINGS</small><strong>—</strong><span>Loading</span></div><div class="metric"><small>WORKERS</small><strong>—</strong><span>Loading</span></div><div class="metric"><small>PENDING</small><strong>—</strong><span>Verification</span></div><div class="metric"><small>PAID</small><strong>—</strong><span>Bookings</span></div></div><div class="admin-grid">${[['👷','Worker verification','Review onboarding and approval'],['📍','Live dispatch','Monitor matching and ETA'],['💰','Pricing & commissions','Transparent economics'],['💳','Payments & payouts','Payment adapter status'],['🛡️','Safety cases','Review reported issues'],['🤖','AI console','Review AI routing and support'],['📊','Analytics','Operational metrics'],['⚙️','System health','API and provider readiness']].map((x,i)=>`<div class="card admin-card"><span>${x[0]}</span><h2>${x[1]}</h2><p>${x[2]}</p><button class="btn alt" onclick="adminAction('${esc(x[1])}')">Open module →</button></div>`).join('')}</div>`}
async function adminAction(x){try{const d=await api('/admin/summary');toast(`${x}: ${d.bookings??0} bookings in current environment`,'ok')}catch(e){toast(`${x} opened in preview mode`,'ok')}}
function more(){return `<section class="page-title"><span class="eyebrow">MORE HOMEHERO</span><h1>Everything in one place.</h1><p>Customer, worker and operations modules with a consistent flow.</p></section><div class="module-grid">${[['🤖','AI Assistant','Smart service guidance','ai'],['👤','Profile','Account and settings','profile'],['👷','Worker onboarding','Apply as a professional','apply'],['📋','Bookings','Track every service','bookings'],['🎁','Offers','Save eligible offers','offers'],['🛡️','Safety & support','Get help or report an issue','support'],['⚡','Smart matching','Location-aware dispatch','track'],['🏢','Apartment mode','Future multi-home workflow','home']].map(x=>`<button class="card module-card" onclick="go('${x[3]}')"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small><i>→</i></button>`).join('')}</div>`}
function aiAssistant(){return `<section class="ai-shell"><div class="ai-header"><span class="ai-orb">🤖</span><div><span class="eyebrow">HOMEHERO AI</span><h1>Tell me what is happening.</h1><p>Service selection · booking help · pricing · support.</p><div class="ai-status">● Backend AI routing · OpenRouter / Groq / Cloudflare fallback</div></div></div><div class="suggestions"><button onclick="useAI('My kitchen tap is leaking. Which service do I need?')">Leaking tap</button><button onclick="useAI('How much will a 2 hour cleaning booking cost?')">Cleaning price</button><button onclick="useAI('How do I book a professional?')">How to book</button></div><div class="ai-chat" id="aiout"><div class="ai-message"><span>🤖</span><p>Hi! Describe the home problem and I’ll help you choose the right service and next step.</p></div></div><div class="ai-input"><textarea id="aiq" class="input" rows="2" placeholder="Example: My AC is not cooling…"></textarea><button class="btn primary glow" onclick="askAI()">Send ↑</button></div></section>`}
function useAI(q){document.getElementById('aiq').value=q;askAI()}
async function askAI(){const input=document.getElementById('aiq'),q=input?.value.trim();if(!q)return toast('Tell HomeHero AI what you need','error');const out=document.getElementById('aiout');out.insertAdjacentHTML('beforeend',`<div class="user-message"><span>You</span><p>${esc(q)}</p></div>`);input.value='';out.insertAdjacentHTML('beforeend',`<div class="ai-message thinking"><span>🤖</span><p>Analysing your request…</p></div>`);out.scrollTop=out.scrollHeight;try{const d=await api('/ai/chat',{method:'POST',body:JSON.stringify({messages:[{role:'user',content:q}],task:'service-support'})});out.querySelector('.thinking')?.remove();out.insertAdjacentHTML('beforeend',`<div class="ai-message"><span>🤖</span><p><b>${esc(d.provider==='local'?'HomeHero Smart Support':'HomeHero AI')}</b><br>${esc(d.text||'No response available.')}</p></div>`)}catch(e){out.querySelector('.thinking')?.remove();out.insertAdjacentHTML('beforeend',`<div class="ai-message"><span>🤖</span><p>${esc(localAI(q))}</p></div>`)}out.scrollTop=out.scrollHeight}
function applyWorker(){return `<section class="page-title"><span class="eyebrow">JOIN HOMEHERO</span><h1>Become a trusted <em>professional.</em></h1><p>Submit your details for operations review. Production KYC and payout providers can be connected on the backend.</p></section><div class="card form-card worker-form"><label class="field-label">Full name</label><input id="wname" class="input" placeholder="Your full name"><label class="field-label">Mobile number</label><input id="wphone" class="input" placeholder="10-digit mobile" inputmode="numeric"><label class="field-label">Services / skills</label><input id="wskills" class="input" placeholder="plumber, electrician, AC"><label class="field-label">Experience</label><textarea id="wexp" class="input" rows="4" placeholder="Tell us about your experience"></textarea><button class="btn primary glow full" onclick="submitWorker()">Submit application →</button></div>`}
async function submitWorker(){const name=document.getElementById('wname')?.value.trim(),phone=document.getElementById('wphone')?.value.replace(/\D/g,''),skills=document.getElementById('wskills')?.value.trim();if(!name||phone?.length!==10||!skills)return toast('Enter name, valid mobile and skills','error');setLoading(true,'Submitting professional application…');try{const d=await api('/workers/apply',{method:'POST',body:JSON.stringify({name,phone,services:skills.split(',').map(x=>x.trim()).filter(Boolean),experience:document.getElementById('wexp')?.value.trim()||''})});toast(d.message||'Application submitted','ok');go('worker')}catch(e){toast(e.message,'error')}finally{setLoading(false)}}
function locationRequest(){
 if(!navigator.geolocation)return toast('Location is not supported by this browser','error');
 setLoading(true,'Requesting location permission…');
 navigator.geolocation.getCurrentPosition(p=>{state.coords={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy};saveLocal();document.getElementById('locpill')?.replaceChildren(document.createTextNode('Location enabled'));setLoading(false);toast('Location enabled for matching','ok')},e=>{setLoading(false);toast(e.code===1?'Location permission was denied. You can still enter your address manually.':'Could not get location. Please try again.','error')},{enableHighAccuracy:true,timeout:10000,maximumAge:30000});
}
function boot(){loadLocal();state.notifyEnabled=localStorage.hh_notify==='1';render();if(state.logged)setTimeout(()=>locationRequest(),250)}
boot();
